import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          LoginPage(),
        ]),
      ),
    );
  }
}

class LoginPage extends StatelessWidget {
  const LoginPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1920,
          height: 573,
          padding: const EdgeInsets.symmetric(horizontal: 776, vertical: 16),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: 368,
                padding: const EdgeInsets.only(left: 4, right: 4, bottom: 2),
                clipBehavior: Clip.antiAlias,
                decoration: const BoxDecoration(),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    SizedBox(
                      width: 360,
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Sign in or create an account',
                            style: TextStyle(
                              color: Color(0xFF1A1A1A),
                              fontSize: 19,
                              fontFamily: 'Noto Sans SC',
                              fontWeight: FontWeight.w700,
                              height: 28,
                            ),
                          ),
                          const SizedBox(height: 32),
                          SizedBox(
                            height: 274,
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                SizedBox(
                                  height: 60,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [
                                      const Text(
                                        'Email address',
                                        style: TextStyle(
                                          color: Color(0xFF1A1A1A),
                                          fontSize: 14,
                                          fontFamily: 'Segoe UI',
                                          fontWeight: FontWeight.w400,
                                          height: 20,
                                        ),
                                      ),
                                      const SizedBox(height: 4),
                                      Expanded(
                                        child: Container(
                                          width: 360,
                                          padding: const EdgeInsets.only(
                                              top: 8,
                                              left: 8,
                                              right: 8,
                                              bottom: 9),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 360,
                                                height: 36,
                                                decoration: ShapeDecoration(
                                                  color: Colors.white,
                                                  shape: RoundedRectangleBorder(
                                                    side: const BorderSide(
                                                        width: 1,
                                                        color:
                                                            Color(0xFF006CE4)),
                                                    borderRadius:
                                                        BorderRadius.circular(
                                                            4),
                                                  ),
                                                ),
                                              ),
                                              Container(
                                                height: 19,
                                                padding: const EdgeInsets.only(
                                                    right: 191),
                                                clipBehavior: Clip.antiAlias,
                                                decoration:
                                                    const BoxDecoration(),
                                                child: const Row(
                                                  mainAxisSize:
                                                      MainAxisSize.min,
                                                  mainAxisAlignment:
                                                      MainAxisAlignment.start,
                                                  crossAxisAlignment:
                                                      CrossAxisAlignment.start,
                                                  children: [
                                                    Text(
                                                      'Enter your email address',
                                                      style: TextStyle(
                                                        color:
                                                            Color(0xFF757575),
                                                        fontSize: 14,
                                                        fontFamily: 'Segoe UI',
                                                        fontWeight:
                                                            FontWeight.w400,
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                const SizedBox(height: 16),
                                Container(
                                  width: 360,
                                  padding: const EdgeInsets.only(
                                    top: 12,
                                    left: 113.19,
                                    right: 113.81,
                                    bottom: 12,
                                  ),
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(4)),
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 360,
                                        height: 48,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF006CE4),
                                          shape: RoundedRectangleBorder(
                                            side: const BorderSide(
                                                width: 0.50,
                                                color: Color(0xFF006CE4)),
                                            borderRadius:
                                                BorderRadius.circular(4),
                                          ),
                                        ),
                                      ),
                                      const Text(
                                        'Continue with email',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.white,
                                          fontSize: 15,
                                          fontFamily: 'Segoe UI',
                                          fontWeight: FontWeight.w400,
                                          height: 24,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                const SizedBox(height: 16),
                                SizedBox(
                                  height: 134,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [
                                      Container(
                                        padding:
                                            const EdgeInsets.only(bottom: 2),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment:
                                              MainAxisAlignment.center,
                                          crossAxisAlignment:
                                              CrossAxisAlignment.center,
                                          children: [
                                            Container(
                                              width: 87.55,
                                              height: 1,
                                              clipBehavior: Clip.antiAlias,
                                              decoration: const BoxDecoration(
                                                  color: Color(0xFFE7E7E7)),
                                            ),
                                            const SizedBox(width: 8),
                                            Container(
                                              height: double.infinity,
                                              padding: const EdgeInsets.only(
                                                  right: 10.91),
                                              child: const Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment:
                                                    MainAxisAlignment.start,
                                                crossAxisAlignment:
                                                    CrossAxisAlignment.start,
                                                children: [
                                                  Text(
                                                    'or use one of these options',
                                                    style: TextStyle(
                                                      color: Color(0xFF1A1A1A),
                                                      fontSize: 13,
                                                      fontFamily: 'Segoe UI',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 20,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            const SizedBox(width: 8),
                                            Container(
                                              width: 87.55,
                                              height: 1,
                                              clipBehavior: Clip.antiAlias,
                                              decoration: const BoxDecoration(
                                                  color: Color(0xFFE7E7E7)),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: 360,
                                        padding: const EdgeInsets.only(
                                          top: 24,
                                          left: 40,
                                          right: 40,
                                          bottom: 16,
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment:
                                              MainAxisAlignment.center,
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            Container(
                                              height: 72,
                                              padding: const EdgeInsets.all(24),
                                              decoration: ShapeDecoration(
                                                shape: RoundedRectangleBorder(
                                                  side: const BorderSide(
                                                      width: 0.50,
                                                      color: Color(0xFFE7E7E7)),
                                                  borderRadius:
                                                      BorderRadius.circular(4),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment:
                                                    MainAxisAlignment.center,
                                                crossAxisAlignment:
                                                    CrossAxisAlignment.start,
                                                children: [
                                                  Container(
                                                    height: 24,
                                                    clipBehavior:
                                                        Clip.antiAlias,
                                                    decoration:
                                                        const BoxDecoration(),
                                                    child: const Row(
                                                      mainAxisSize:
                                                          MainAxisSize.min,
                                                      mainAxisAlignment:
                                                          MainAxisAlignment
                                                              .center,
                                                      crossAxisAlignment:
                                                          CrossAxisAlignment
                                                              .start,
                                                      children: [
                                                        SizedBox(
                                                          height: 24,
                                                          child: Row(
                                                            mainAxisSize:
                                                                MainAxisSize
                                                                    .min,
                                                            mainAxisAlignment:
                                                                MainAxisAlignment
                                                                    .start,
                                                            crossAxisAlignment:
                                                                CrossAxisAlignment
                                                                    .start,
                                                            children: [],
                                                          ),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            const SizedBox(width: 32),
                                            Container(
                                              height: 72,
                                              padding: const EdgeInsets.all(24),
                                              decoration: ShapeDecoration(
                                                shape: RoundedRectangleBorder(
                                                  side: const BorderSide(
                                                      width: 0.50,
                                                      color: Color(0xFFE7E7E7)),
                                                  borderRadius:
                                                      BorderRadius.circular(4),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment:
                                                    MainAxisAlignment.center,
                                                crossAxisAlignment:
                                                    CrossAxisAlignment.start,
                                                children: [
                                                  Container(
                                                    height: 24,
                                                    clipBehavior:
                                                        Clip.antiAlias,
                                                    decoration:
                                                        const BoxDecoration(),
                                                    child: const Row(
                                                      mainAxisSize:
                                                          MainAxisSize.min,
                                                      mainAxisAlignment:
                                                          MainAxisAlignment
                                                              .center,
                                                      crossAxisAlignment:
                                                          CrossAxisAlignment
                                                              .start,
                                                      children: [
                                                        SizedBox(
                                                          width: 24,
                                                          height: 24,
                                                          child: Stack(
                                                              children: []),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            const SizedBox(width: 32),
                                            Container(
                                              height: 72,
                                              padding: const EdgeInsets.all(24),
                                              decoration: ShapeDecoration(
                                                shape: RoundedRectangleBorder(
                                                  side: const BorderSide(
                                                      width: 0.50,
                                                      color: Color(0xFFE7E7E7)),
                                                  borderRadius:
                                                      BorderRadius.circular(4),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment:
                                                    MainAxisAlignment.center,
                                                crossAxisAlignment:
                                                    CrossAxisAlignment.start,
                                                children: [
                                                  Container(
                                                    height: 24,
                                                    clipBehavior:
                                                        Clip.antiAlias,
                                                    decoration:
                                                        const BoxDecoration(),
                                                    child: Row(
                                                      mainAxisSize:
                                                          MainAxisSize.min,
                                                      mainAxisAlignment:
                                                          MainAxisAlignment
                                                              .center,
                                                      crossAxisAlignment:
                                                          CrossAxisAlignment
                                                              .start,
                                                      children: [
                                                        Container(
                                                          height: 24,
                                                          padding:
                                                              const EdgeInsets
                                                                      .symmetric(
                                                                  horizontal:
                                                                      2.37,
                                                                  vertical:
                                                                      0.56),
                                                          child: const Row(
                                                            mainAxisSize:
                                                                MainAxisSize
                                                                    .min,
                                                            mainAxisAlignment:
                                                                MainAxisAlignment
                                                                    .start,
                                                            crossAxisAlignment:
                                                                CrossAxisAlignment
                                                                    .start,
                                                            children: [],
                                                          ),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),
              SizedBox(
                height: 189,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      width: 360,
                      height: 69,
                      decoration: const BoxDecoration(
                        border: Border(
                          left: BorderSide(color: Color(0xFFE7E7E7)),
                          top:
                              BorderSide(width: 0.50, color: Color(0xFFE7E7E7)),
                          right: BorderSide(color: Color(0xFFE7E7E7)),
                          bottom: BorderSide(color: Color(0xFFE7E7E7)),
                        ),
                      ),
                      child: const Stack(
                        children: [
                          Positioned(
                            left: 9.67,
                            top: 17,
                            child: Text(
                              'By signing in or creating an account, you agree with our ',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF1A1A1A),
                                fontSize: 12,
                                fontFamily: 'Segoe UI',
                                fontWeight: FontWeight.w400,
                                height: 18,
                              ),
                            ),
                          ),
                          Positioned(
                            left: 89.61,
                            top: 19,
                            child: SizedBox(
                              width: 261.70,
                              height: 32,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 217.69,
                                    top: -2,
                                    child: Text(
                                      'Terms &',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF006CE4),
                                        fontSize: 12,
                                        fontFamily: 'Segoe UI',
                                        fontWeight: FontWeight.w400,
                                        height: 18,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 2,
                                    top: 16,
                                    child: Text(
                                      'Conditions',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF006CE4),
                                        fontSize: 11,
                                        fontFamily: 'Segoe UI',
                                        fontWeight: FontWeight.w400,
                                        height: 18,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          Positioned(
                            left: 148.31,
                            top: 35,
                            child: Text.rich(
                              TextSpan(
                                children: [
                                  TextSpan(
                                    text: ' and ',
                                    style: TextStyle(
                                      color: Color(0xFF1A1A1A),
                                      fontSize: 12,
                                      fontFamily: 'Segoe UI',
                                      fontWeight: FontWeight.w400,
                                      height: 18,
                                    ),
                                  ),
                                  TextSpan(
                                    text: 'Privacy Statement',
                                    style: TextStyle(
                                      color: Color(0xFF006CE4),
                                      fontSize: 12,
                                      fontFamily: 'Segoe UI',
                                      fontWeight: FontWeight.w400,
                                      height: 18,
                                    ),
                                  ),
                                ],
                              ),
                              textAlign: TextAlign.center,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: 360,
                      padding: const EdgeInsets.only(
                        top: 17,
                        left: 28.25,
                        right: 28.75,
                        bottom: 16,
                      ),
                      decoration: const BoxDecoration(
                        border: Border(
                          left: BorderSide(color: Color(0xFFE7E7E7)),
                          top:
                              BorderSide(width: 0.50, color: Color(0xFFE7E7E7)),
                          right: BorderSide(color: Color(0xFFE7E7E7)),
                          bottom: BorderSide(color: Color(0xFFE7E7E7)),
                        ),
                      ),
                      child: const Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Do not sell my personal information – California residents only',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF006CE4),
                              fontSize: 11,
                              fontFamily: 'Segoe UI',
                              fontWeight: FontWeight.w400,
                              height: 18,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: 360,
                      padding: const EdgeInsets.only(top: 17, bottom: 16),
                      decoration: const BoxDecoration(
                        border: Border(
                          left: BorderSide(color: Color(0xFFE7E7E7)),
                          top:
                              BorderSide(width: 0.50, color: Color(0xFFE7E7E7)),
                          right: BorderSide(color: Color(0xFFE7E7E7)),
                          bottom: BorderSide(color: Color(0xFFE7E7E7)),
                        ),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Container(
                            height: 36,
                            padding: const EdgeInsets.only(
                                left: 74.61, right: 74.39),
                            child: const Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'All rights reserved.\nCopyright (2006-2023) – Booking.com™',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Color(0xFF1A1A1A),
                                    fontSize: 12,
                                    fontFamily: 'Segoe UI',
                                    fontWeight: FontWeight.w400,
                                    height: 18,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
